import 'package:flutter/material.dart';
import 'package:talabat/models/store.model.dart';
import 'package:talabat/models/food.model.dart';
import 'package:talabat/models/option.model.dart';
import 'package:talabat/services/store.service.dart';

class AdminStorePage extends StatefulWidget {
  const AdminStorePage({super.key});

  @override
  State<AdminStorePage> createState() => _AdminStorePageState();
}

class _AdminStorePageState extends State<AdminStorePage> {
  final storeService = StoreService();

  final _storeNameController = TextEditingController();
  final _imageUrlController = TextEditingController();
  final _categoriesController = TextEditingController();

  final _foodNameController = TextEditingController();
  final _foodCategoryController = TextEditingController();
  final _foodImageUrlController = TextEditingController();
  final List<Option> _options = [];

  String? selectedStoreId;

  void _createStore() async {
    final store = Store(
      id: '', // will be generated by Firestore
      storeName: _storeNameController.text,
      storeImageUrl: _imageUrlController.text,
      categories: _categoriesController.text.split(','),
      isTrend: true,
    );
    await storeService.createStore(store);
    _storeNameController.clear();
    _imageUrlController.clear();
    _categoriesController.clear();
  }

  void _addFood() async {
    if (selectedStoreId == null) return;

    final food = FoodItem(
      id: '',
      name: _foodNameController.text,
      category: _foodCategoryController.text,
      imageUrl: _foodImageUrlController.text,
      options: _options.toList(),
    );

    await storeService.addFood(selectedStoreId!, food);

    _foodNameController.clear();
    _foodCategoryController.clear();
    _foodImageUrlController.clear();
    _options.clear();
    setState(() {}); // refresh
  }

  void _addOption(String name, int price) {
    final id = _options.length + 1;
    _options.add(Option(id: id, name: name, price: price));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Admin - Manage Stores')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Create Store',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            TextField(
                controller: _storeNameController,
                decoration: const InputDecoration(labelText: 'Store Name')),
            TextField(
                controller: _imageUrlController,
                decoration: const InputDecoration(labelText: 'Image URL')),
            TextField(
                controller: _categoriesController,
                decoration: const InputDecoration(
                    labelText: 'Categories (comma separated)')),
            ElevatedButton(
                onPressed: _createStore, child: const Text('Add Store')),
            const Divider(height: 40),
            const Text('Add Food to Store',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            StreamBuilder<List<Store>>(
              stream: storeService.getStores(),
              builder: (context, snapshot) {
                if (!snapshot.hasData) return const CircularProgressIndicator();
                return DropdownButton<String>(
                  hint: const Text('Select Store'),
                  value: selectedStoreId,
                  onChanged: (value) => setState(() => selectedStoreId = value),
                  items: snapshot.data!.map((store) {
                    return DropdownMenuItem(
                        value: store.id, child: Text(store.storeName));
                  }).toList(),
                );
              },
            ),
            TextField(
                controller: _foodNameController,
                decoration: const InputDecoration(labelText: 'Food Name')),
            TextField(
                controller: _foodCategoryController,
                decoration: const InputDecoration(labelText: 'Category')),
            TextField(
                controller: _foodImageUrlController,
                decoration: const InputDecoration(labelText: 'Image URL')),
            const SizedBox(height: 10),
            TextButton(
              onPressed: () => _addOption('Default Option', 5000),
              child: const Text('+ Add Dummy Option'),
            ),
            Text('Options Count: ${_options.length}'),
            ElevatedButton(onPressed: _addFood, child: const Text('Add Food')),
          ],
        ),
      ),
    );
  }
}
