// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xsAPnfcMtEL4EDq-_YZkUGe9vct7JCU',
    appId: '1:562638784244:web:2bb50e52f61b6061c0c0a1',
    messagingSenderId: '562638784244',
    projectId: 'talabat-clone-a601f',
    authDomain: 'talabat-clone-a601f.firebaseapp.com',
    storageBucket: 'talabat-clone-a601f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZATsSMW7dOH3B1kNvGXzy1K3-tUvHII',
    appId: '1:562638784244:android:d3ce9352a140cb5ac0c0a1',
    messagingSenderId: '562638784244',
    projectId: 'talabat-clone-a601f',
    storageBucket: 'talabat-clone-a601f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYIJa06AxQPR1JkX8QwFwyyw-pQ36_gqI',
    appId: '1:562638784244:ios:5131631bd4621a9fc0c0a1',
    messagingSenderId: '562638784244',
    projectId: 'talabat-clone-a601f',
    storageBucket: 'talabat-clone-a601f.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYIJa06AxQPR1JkX8QwFwyyw-pQ36_gqI',
    appId: '1:562638784244:ios:5131631bd4621a9fc0c0a1',
    messagingSenderId: '562638784244',
    projectId: 'talabat-clone-a601f',
    storageBucket: 'talabat-clone-a601f.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9xsAPnfcMtEL4EDq-_YZkUGe9vct7JCU',
    appId: '1:562638784244:web:46f29a8cc2eacb40c0c0a1',
    messagingSenderId: '562638784244',
    projectId: 'talabat-clone-a601f',
    authDomain: 'talabat-clone-a601f.firebaseapp.com',
    storageBucket: 'talabat-clone-a601f.firebasestorage.app',
  );
}
